- name: Check if helm is installed
  ansible.builtin.command: which helm
  register: helm_binary
  changed_when: false
  failed_when: false

- name: Download Helm install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0755'
  when: helm_binary.rc != 0

- name: Install Helm
  ansible.builtin.command: /tmp/get_helm.sh
  when: helm_binary.rc != 0

- name: Check Helm version
  ansible.builtin.command: helm version
  register: helm_version
  changed_when: false

- name: Show Helm version
  ansible.builtin.debug:
    var: helm_version.stdout

